// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/student.proto

package com.baeldung.protobuf;

public interface CourseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:baeldung.Course)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string course_name = 2;</code>
   * @return The courseName.
   */
  java.lang.String getCourseName();
  /**
   * <code>string course_name = 2;</code>
   * @return The bytes for courseName.
   */
  com.google.protobuf.ByteString
      getCourseNameBytes();

  /**
   * <code>repeated .baeldung.Student student = 3;</code>
   */
  java.util.List<com.baeldung.protobuf.Student> 
      getStudentList();
  /**
   * <code>repeated .baeldung.Student student = 3;</code>
   */
  com.baeldung.protobuf.Student getStudent(int index);
  /**
   * <code>repeated .baeldung.Student student = 3;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .baeldung.Student student = 3;</code>
   */
  java.util.List<? extends com.baeldung.protobuf.StudentOrBuilder> 
      getStudentOrBuilderList();
  /**
   * <code>repeated .baeldung.Student student = 3;</code>
   */
  com.baeldung.protobuf.StudentOrBuilder getStudentOrBuilder(
      int index);
}
