// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/student.proto

package com.baeldung.protobuf;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:baeldung.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string first_name = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 3;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 3;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
   */
  java.util.List<com.baeldung.protobuf.Student.PhoneNumber> 
      getPhoneList();
  /**
   * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
   */
  com.baeldung.protobuf.Student.PhoneNumber getPhone(int index);
  /**
   * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
   */
  int getPhoneCount();
  /**
   * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
   */
  java.util.List<? extends com.baeldung.protobuf.Student.PhoneNumberOrBuilder> 
      getPhoneOrBuilderList();
  /**
   * <code>repeated .baeldung.Student.PhoneNumber phone = 5;</code>
   */
  com.baeldung.protobuf.Student.PhoneNumberOrBuilder getPhoneOrBuilder(
      int index);
}
